VI2EN = "vi2en"
EN2VI = "en2vi"
MODE = EN2VI

BERT_REPO = "bert-base-uncased"
PhoBERT_REPO = "vinai/phobert-base"

MAX_LENGTH = 25
EMBEDDING_SIZE = 32
N_TRANSFORMER_LAYERS = 4
N_HEADS = 4
DIM_FEEDFORWARD = 256

N_EPOCHS = 100
BATCH_SIZE = 128
