VI2EN = "vi2en"
EN2VI = "en2vi"
MODE = EN2VI

BERT_REPO = "bert-base-uncased"
BERT_BOS_TOKEN = '[CLS]'
BERT_EOS_TOKEN = '[SEP]'
BERT_PADDING_TOKEN = '[PAD]'
BERT_BOS_INDEX = 101
BERT_EOS_INDEX = 102
BERT_PADDING_INDEX = 0

PhoBERT_REPO = "vinai/phobert-base"
PhoBERT_BOS_TOKEN = '<s>'
PhoBERT_EOS_TOKEN = '</s>'
PhoBERT_PADDING_TOKEN = '<pad>'
PhoBERT_BOS_INDEX = 0
PhoBERT_EOS_INDEX = 2
PhoBERT_PADDING_INDEX = 1

MAX_LENGTH = 12
EMBEDDING_SIZE = 768
N_TRANSFORMER_LAYERS = 4
N_HEADS = 4
DIM_FEEDFORWARD = 2048

N_EPOCHS = 100
BATCH_SIZE = 8
